-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 19:47:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `Res Halls` (
  `ID` INTEGER NOT NULL,
  `Name` TEXT NULL,
  `Capacity` TEXT NULL,
  PRIMARY KEY (`ID`))

CREATE TABLE IF NOT EXISTS `Groups` (
  `ID` INTEGER NOT NULL,
  `StudentIDs` TEXT NULL,
  PRIMARY KEY (`ID`));


CREATE TABLE IF NOT EXISTS `Students` (
  `ID` INTEGER NOT NULL,
  `Name` TEXT NULL,
  `Credits` TEXT NULL,
  `GPA` TEXT NULL,
  `RoomID` INTEGER NULL,
  'Password' TEXT NOT NULL,
  PRIMARY KEY (`ID`));



CREATE TABLE IF NOT EXISTS `ResHallX` (
  `RoomID` INTEGER NOT NULL,
  `OccupiedBy` TEXT NULL,
  PRIMARY KEY (`RoomID`));



CREATE TABLE IF NOT EXISTS `Queues` (
  `ID` INTEGEREGER NOT NULL,
  `ResHall` TEXT NULL,
  `GroupID` TEXT NULL,
  PRIMARY KEY (`ID`));



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
